var searchData=
[
  ['get_5fcutting_5fplane',['get_cutting_plane',['../test__split__order_8cc.html#a13ef77cb1e6dd86e99fb454174c534cc',1,'get_cutting_plane(Tangram::Point&lt; Dim &gt; &amp;plane_pt, Tangram::Vector&lt; Dim &gt; &amp;normal):&#160;test_split_order.cc'],['../test__split__r2d_8cc.html#ac105d500d1d9f8e2ea737c9b85c993b2',1,'get_cutting_plane(Tangram::Point&lt; 2 &gt; &amp;plane_pt, Tangram::Vector&lt; 2 &gt; &amp;normal):&#160;test_split_r2d.cc']]],
  ['get_5fintersection_5fmoments',['get_intersection_moments',['../namespaceTangram.html#af02fba4de7b9b6cdae6e0f7b655d96b9',1,'Tangram::get_intersection_moments(const MatPoly&lt; 2 &gt; &amp;mat_poly, const r2d_poly &amp;r2dpoly, std::vector&lt; double &gt; &amp;intersection_moments, bool convex_matpoly=false)'],['../namespaceTangram.html#ad580bc2bc65a62b3650d30447117732a',1,'Tangram::get_intersection_moments(const MatPoly&lt; 3 &gt; &amp;mat_poly, const r3d_poly &amp;r3dpoly, std::vector&lt; double &gt; &amp;intersection_moments, bool convex_matpoly=false)']]],
  ['get_5fith_5fmatpoly',['get_ith_matpoly',['../classTangram_1_1CellMatPoly.html#ad379b1f5ec52c95be6945cd33256ae0b',1,'Tangram::CellMatPoly::get_ith_matpoly(int matpoly_id) const'],['../classTangram_1_1CellMatPoly.html#a68f3509784ebadd311cbb060e9d13c07',1,'Tangram::CellMatPoly::get_ith_matpoly(int matpoly_id) const'],['../classTangram_1_1CellMatPoly.html#a9a9a28e29c56b87a4fca5c90bd68aee4',1,'Tangram::CellMatPoly::get_ith_matpoly(int matpoly_id) const']]],
  ['get_5fmat_5fsym_5fdiff_5fvol',['get_mat_sym_diff_vol',['../get__mat__sym__diff__vol_8h.html#a99a3fb48bfd1ba830dee9a90e4709896',1,'get_mat_sym_diff_vol(const std::vector&lt; std::vector&lt; r3d_poly &gt; &gt; &amp;reference_mat_polys, const std::vector&lt; int &gt; &amp;ref_mat_ids, const std::vector&lt; double &gt; &amp;ref_mat_vol, const std::shared_ptr&lt; Tangram::CellMatPoly&lt; 3 &gt; &gt; &amp;result_ptr, std::vector&lt; double &gt; &amp;mat_sym_diff_vol, bool convex_matpolys=false):&#160;get_mat_sym_diff_vol.h'],['../get__mat__sym__diff__vol_8h.html#a93e6c00f64ab1cd41e3bfc5718f67709',1,'get_mat_sym_diff_vol(const std::vector&lt; std::vector&lt; r2d_poly &gt; &gt; &amp;reference_mat_polys, const std::vector&lt; int &gt; &amp;ref_mat_ids, const std::vector&lt; double &gt; &amp;ref_mat_vol, const std::shared_ptr&lt; Tangram::CellMatPoly&lt; 2 &gt; &gt; &amp;result_ptr, std::vector&lt; double &gt; &amp;mat_sym_diff_vol, bool convex_matpolys=false):&#160;get_mat_sym_diff_vol.h']]],
  ['get_5fmaterial_5fmoments',['get_material_moments',['../get__material__moments_8h.html#ac0c93b6da04bc9fa07409f5af57631ae',1,'get_material_moments(const Mesh_Wrapper &amp;mesh, const std::vector&lt; Tangram::Plane_t&lt; 3 &gt; &gt; &amp;planar_interfaces, const std::vector&lt; int &gt; &amp;material_IDs, std::vector&lt; int &gt; &amp;cell_num_mats, std::vector&lt; int &gt; &amp;cell_mat_ids, std::vector&lt; double &gt; &amp;cell_mat_volfracs, std::vector&lt; Tangram::Point&lt; 3 &gt; &gt; &amp;cell_mat_centroids, std::vector&lt; std::vector&lt; std::vector&lt; r3d_poly &gt; &gt; &gt; &amp;reference_mat_polys, bool decompose_cells=true):&#160;get_material_moments.h'],['../get__material__moments_8h.html#ad61a0c14d545ed43df9e1ff8426a1d1b',1,'get_material_moments(const Mesh_Wrapper &amp;mesh, const std::vector&lt; Tangram::Plane_t&lt; 2 &gt; &gt; &amp;linear_interfaces, const std::vector&lt; int &gt; &amp;material_IDs, std::vector&lt; int &gt; &amp;cell_num_mats, std::vector&lt; int &gt; &amp;cell_mat_ids, std::vector&lt; double &gt; &amp;cell_mat_volfracs, std::vector&lt; Tangram::Point&lt; 2 &gt; &gt; &amp;cell_mat_centroids, std::vector&lt; std::vector&lt; std::vector&lt; r2d_poly &gt; &gt; &gt; &amp;reference_mat_polys, bool decompose_cells=true):&#160;get_material_moments.h']]],
  ['get_5fmatpolys',['get_matpolys',['../classTangram_1_1CellMatPoly.html#a32ce37824ceb0a567b6d451926637e97',1,'Tangram::CellMatPoly']]],
  ['get_5fplane_5fposition',['get_plane_position',['../classTangram_1_1MOF.html#ac66fe2b8b89d6c716a45edbf91e636a5',1,'Tangram::MOF::get_plane_position()'],['../classTangram_1_1VOF.html#a0df7b94f53e2d9374df3d881e6e706b0',1,'Tangram::VOF::get_plane_position()']]]
];
